set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(CMAKE_SYSROOT /usr/arm-linux-gnueabi)

set(HOST_TOOL_PATH /usr/bin)
set(CMAKE_C_COMPILER ${HOST_TOOL_PATH}/arm-linux-gnueabi-gcc)
set(CMAKE_CXX_COMPILER ${HOST_TOOL_PATH}/arm-linux-gnueabi-g++)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
